let numero1=Number(prompt("Digite um numero"))
let numero2=Number(prompt("Digite um numero"))
let operacao = prompt("Qual operação")

if (operacao == "+")
    console.log (numero1 + numero2)
    else if (operacao == "-")
        console.log (numero1 - numero2)
        else if (operacao == "*")
            console.log (numero1 * numero2)
            else if (operacao == "/")
                console.log (numero1 / numero2)
            else console.log("Operação inválida")